---
language: python
services:
  - docker

# Install ansible
addons:
  apt:
    packages:
      - python-pip

install:
  # Install molecule
  - pip install molecule

  # Check molecule version
  - molecule --version

  # Check ansible version
  - ansible --version

script:
  # Run tests
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
